# Site settings
title: Web Site do Wellington
email: wwagner@virtual.ufc.br
description: > # this means to ignore newlines until "baseurl:"
  Este é meu web site.
baseurl: "/www" # the subpath of your site, e.g. /blog/
url: "http://wwagner33.github.io" # the base hostname & protocol for your site
github_username:  wwagner33

# Build settings
markdown: kramdown
permalink: /:year/:title:output_ext

defaults:
  - scope:
      path: "https://wwwagner33.github.io"
    values:
      headers:
        Access-Control-Allow-Origin: "https://dominio-do-lattes-api.com https://dominio-do-dblp-api.com"
